### ISSUE TITLE
README and Grammar suggestions

### ISSUE THREAD

**Issue by rtoal** [cbillingham/roo#2]
Good job on the README.

Two things:
- You only exlcude the control characters U+0000 through U+001F from strings, why not the others?
- Your grammar supports the expression `Var.id` but I don't know what this refers to. I don't see any objects in your language.

**Comment by jtfennell** [comment]
Control character exclusion updated

**Comment by cbillingham** [comment]
we do have objects there just written with class like swift
`ObjectDec    ::= 'class' id Body`

but I imagine will also want to use this type of expression for map as well

```
x = {name:"Bob"}
x.name                       # is Bob
```
